id: I5557D505
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:03:01+00:00'
last_modified: '2022-06-08T08:12:40.809184+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22684
  title: འཕགས་པ་ནོར་ཕྱུགས་སྐྱོང་ཞིང་སྤེལ་བ་ཞེས་བྱ་བའི་གཟུངས་དང་གཙང་མ་ཀླུ་འབུམ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    450E:
      image_group_id: I1KG22927
      title: ''
      total_pages: 90
      order: 1
      base_file: 450E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
