id: P008246
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22684
  title: འཕགས་པ་ནོར་ཕྱུགས་སྐྱོང་ཞིང་སྤེལ་བ་ཞེས་བྱ་བའི་གཟུངས་དང་གཙང་མ་ཀླུ་འབུམ་དཀར་པོ།
  author: ''
  volumes:
    81d6596978e64d779b7b35d2bec04f99:
      image_group_id: I1KG22927
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
